### ISSUE TITLE
VNet integration feature not available in My Web Apps for container

### ISSUE THREAD

**Issue by kysaitou** [Azure/app-service-linux-docs#23]
Senario: 
I am running a custom container app on Web Apps for Container.
I want to use this Web Apps to communicate with virtual machines on VNet by using the VNet integration function.

Issue:
When I try to configure App Service Plan Networking in the Azure portal, it is grayed out and cannot be configured.
The following message will be displayed on the screen.

> This feature is not supported for your current plan.

My App Service Plan is Standard plan.

I tried the following, but they are all in the same state.
- Upgrade to PremiumV2
- Create a new Premium V2 App Service Plan

**Comment by rayamoh** [comment]
I am seeing same issue. @kysaitou  - Have you found any solution , please share.

**Comment by kysaitou** [comment]
@rayamoh 
Thank you for your comment.

I have found a solution through support answers.
In order to use the features of the VNet integration, you must configure the Network in App Service, not App Service Plan.

Also, on App Services using Docker Compose, you can't use the VNet integration.

**Comment by rayamoh** [comment]
Thanks @kysaitou .  I am trying from App service and it is not listing any VNETs. Could be due to App service Linux Plan does not support VNET in production work loads. Mine is FLask/Python app and publishing code option (not docker). Please share if you are using Docker option or windows App service plan. And if it is python , can you share steps used for VNET
